ARG version
FROM almalinux:${version:-9}
#ARG CORUSE
#ARG TRAINER
ARG course=Anshu
ARG trainer=Swathi
ARG DURATION=120hours
ENV duration=${DURATION}
RUN echo "course is ${course}, and trainer is ${trainer}, duration is ${DURATION}"
CMD ["sleep","100"]