ARG version
FROM almalinux:${version:-9}
#ARG CORUSE
#ARG TRAINER
ARG CORUSE=Anshu
ARG TRAINER=Swathi
ENV DURATION=120hours
RUN echo "course is ${CORUSE}, and trainer is ${TRAINER},duration is ${DURATION}"
CMD ["sleep","100"]