ARG version
FROM almalinux:${version:-9}
#ARG CORUSE
#ARG TRAINER
ARG course=Anshu
ARG trainer=Swathi
ENV DURATION=120hours
RUN echo "course is ${course}, and trainer is ${trainer}, duration is ${DURATION}"
CMD ["sleep","100"]